from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


LIMITATION_TEXT = (
    "This report is generated by a clinical decision-support prototype. "
    "It does not diagnose ASD or any speech-language disorder. All transcript, "
    "feature, AI-assisted summary, and report content must be reviewed and "
    "signed off by a qualified therapist or clinician."
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class ReviewStatus(str, Enum):
    draft = "Draft"
    needs_review = "Needs Review"
    attested = "Attested"
    processing = "Processing"
    failed = "Failed"
    ready = "Ready"
    signed_off = "Signed Off"
    withdrawn = "Withdrawn"


class QaStatus(str, Enum):
    not_run = "NOT_RUN"
    pass_ = "PASS"
    warning = "WARNING"
    fail = "FAIL"


class JobStatus(str, Enum):
    queued = "queued"
    processing = "processing"
    transcription_completed = "transcription_completed"
    needs_review = "needs_review"
    failed = "failed"
    cancelled = "cancelled"


class SpeakerCode(str, Enum):
    CHI = "CHI"
    THER = "THER"
    PAR = "PAR"
    INV = "INV"
    UNK = "UNK"


class ChildCaseBase(BaseModel):
    child_code: str
    nickname: str | None = None
    age_months: int = Field(ge=0, le=240)
    language: str = "English"
    consent_status: str = "granted"
    notes: str = ""


class ChildCaseCreate(ChildCaseBase):
    pass


class ChildCaseUpdate(BaseModel):
    nickname: str | None = None
    age_months: int | None = Field(default=None, ge=0, le=240)
    language: str | None = None
    consent_status: str | None = None
    notes: str | None = None


class ChildCase(ChildCaseBase):
    case_id: str
    latest_session_date: str | None = None
    latest_session_status: ReviewStatus = ReviewStatus.draft
    latest_report_status: ReviewStatus = ReviewStatus.draft
    review_priority: str = "low"
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class TherapySessionCreate(BaseModel):
    session_date: str
    session_type: str = "therapy_session"
    notes: str = ""


class TherapySessionUpdate(BaseModel):
    session_date: str | None = None
    session_type: str | None = None
    notes: str | None = None
    status: ReviewStatus | None = None


class TherapySession(BaseModel):
    session_id: str
    case_id: str
    session_date: str
    session_type: str
    notes: str = ""
    status: ReviewStatus = ReviewStatus.draft
    transcript_id: str | None = None
    feature_set_id: str | None = None
    ai_review_id: str | None = None
    report_id: str | None = None
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class TherapyGoalCreate(BaseModel):
    title: str
    target: str = ""
    status: str = "active"
    notes: str = ""


class TherapyGoalUpdate(BaseModel):
    title: str | None = None
    target: str | None = None
    status: str | None = None
    notes: str | None = None


class TherapyGoal(BaseModel):
    goal_id: str
    case_id: str
    title: str
    target: str = ""
    status: str = "active"
    notes: str = ""
    retained: bool = True
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class DependentTier(BaseModel):
    tier: str
    raw_text: str
    line_number: int
    supported: bool = False
    analyzed: bool = False
    parser_action: str = "preserved_not_analyzed"


class OrphanDependentTier(BaseModel):
    tier: str
    raw_text: str
    line_number: int
    parser_action: str = "preserved_unattached"


class Utterance(BaseModel):
    utterance_id: str
    speaker: SpeakerCode | str
    text: str
    start_ms: int | None = None
    end_ms: int | None = None
    unintelligible: bool = False
    notes: str = ""
    confidence: float | None = None
    dependent_tiers: list[DependentTier] = Field(default_factory=list)


class Transcript(BaseModel):
    transcript_id: str
    session_id: str
    case_id: str
    source: str
    raw_text: str
    utterances: list[Utterance] = Field(default_factory=list)
    qa_status: QaStatus = QaStatus.not_run
    qa_issues: list["QaIssue"] = Field(default_factory=list)
    review_status: ReviewStatus = ReviewStatus.needs_review
    therapist_attested: bool = False
    attestation_reason: str = ""
    version: int = 1
    chat_metadata: dict = Field(default_factory=dict)
    orphan_dependent_tiers: list[OrphanDependentTier] = Field(default_factory=list)
    malformed_lines: list[dict] = Field(default_factory=list)
    parser_version: str = "chat-basic-v0.7"
    import_timestamp: datetime = Field(default_factory=utc_now)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class TranscriptManualCreate(BaseModel):
    text: str
    language: str = "English"
    replace_existing: bool = False


class TranscriptUploadCha(BaseModel):
    filename: str
    cha_text: str
    replace_existing: bool = False


class TranscriptPatch(BaseModel):
    utterances: list[Utterance] | None = None
    raw_text: str | None = None
    reviewer_note: str = ""


class TranscriptSplitRequest(BaseModel):
    utterance_id: str
    split_at_character: int = Field(ge=1)


class TranscriptMergeRequest(BaseModel):
    first_utterance_id: str
    second_utterance_id: str


class TranscriptExport(BaseModel):
    transcript_id: str
    filename: str
    cha_text: str


class QaIssue(BaseModel):
    code: str
    severity: str  # "error" | "warning" | "info"
    message: str
    line_id: str | None = None
    field: str | None = None
    blocking: bool = False
    fix_suggestion: str | None = None
    source: str = "backend"
    validation_version: str = "chat-basic-v0.7"
    recommended_action: str | None = None


class QaReport(BaseModel):
    transcript_id: str
    overall_status: QaStatus
    issues: list[QaIssue] = Field(default_factory=list)
    can_extract_features: bool
    validation_version: str = "chat-basic-v0.7"


class AttestationRequest(BaseModel):
    attested_by: str = "Demo Therapist"
    reason: str = "Therapist reviewed transcript quality."
    override_qa_failure: bool = False


class FeatureDefinition(BaseModel):
    feature_name: str
    display_name: str
    description: str
    value_type: str  # "integer" | "float" | "ratio" | "count" | "boolean"
    unit: str
    calculation_method: str
    required_inputs: list[str]
    numerator_definition: str | None = None
    denominator_definition: str | None = None
    default_thresholds: dict | None = None
    limitations: list[str]
    clinical_interpretation_caution: str
    feature_version: str = "features-basic-v0.7"
    provider_name: str = "BasicFeatureProvider"


class FeatureValue(BaseModel):
    name: str  # matches feature_name
    value: float | int | str | bool | None = None
    value_type: str = "count"
    unit: str = "count"
    numerator: float | int | None = None
    denominator: float | int | None = None
    thresholds_used: dict | None = None
    calculation_method: str | None = None
    provider_name: str = "BasicFeatureProvider"
    feature_version: str = "features-basic-v0.7"
    transcript_id: str | None = None
    session_id: str | None = None
    computed_at: datetime = Field(default_factory=utc_now)
    insufficient_data: bool = False
    warnings: list[str] = Field(default_factory=list)
    interpretation_hint: str = "Descriptive language sample value; therapist interpretation required."


class FeatureExtractionRequest(BaseModel):
    force_debug_override: bool = False
    override_reason: str = ""


class FeatureSet(BaseModel):
    feature_set_id: str
    session_id: str
    transcript_id: str
    transcript_version: int
    schema_version: str = "features-basic-v0.7"
    therapist_attested: bool
    extracted_at: datetime = Field(default_factory=utc_now)
    warnings: list[str] = Field(default_factory=list)
    features: list[FeatureValue]
    review_status: ReviewStatus = ReviewStatus.ready
    insufficient_data: bool = False
    provider_name: str = "BasicFeatureProvider"
    config_used: dict = Field(default_factory=dict)


class MlDecisionSupport(BaseModel):
    pattern_cues: list[str] = Field(default_factory=list)
    review_suggestions: list[str] = Field(default_factory=list)
    confidence: Literal["limited", "moderate"] = "limited"
    limitations: list[str] = Field(default_factory=list)
    model_version: str = "research-baseline"
    input_features: dict[str, float | int | str | bool] = Field(default_factory=dict)


class AiAssistanceArea(BaseModel):
    area: str
    summary: str
    contributing_factors: list[str] = Field(default_factory=list)
    recommended_actions: list[str] = Field(default_factory=list)


class AiReview(BaseModel):
    ai_review_id: str
    session_id: str
    summary: str
    assistance_areas: list[AiAssistanceArea] = Field(default_factory=list)
    key_findings: list[str]
    concerns: list[str]
    strengths: list[str]
    limitations: list[str]
    recommended_review_actions: list[str]
    confidence_level: str
    requires_therapist_review: bool = True
    review_priority: str = "low"
    model_name: str = "local-rule-based-assistant"
    model_version: str = "v2-mock"
    prompt_version: str = "v2-safety-001"
    input_transcript_version: int
    feature_set_id: str | None = None
    feature_schema_version: str | None = None
    therapist_review_status: ReviewStatus = ReviewStatus.needs_review
    therapist_notes: str = ""
    rejected_reason: str = ""
    created_at: datetime = Field(default_factory=utc_now)


class AiReviewPatch(BaseModel):
    summary: str | None = None
    key_findings: list[str] | None = None
    concerns: list[str] | None = None
    strengths: list[str] | None = None
    limitations: list[str] | None = None
    recommended_review_actions: list[str] | None = None
    therapist_review_status: ReviewStatus | None = None
    therapist_notes: str | None = None
    rejected_reason: str | None = None


class AudioUploadRequest(BaseModel):
    filename: str
    content_type: str
    size_bytes: int
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None


class AudioFileMetadata(BaseModel):
    audio_file_id: str
    session_id: str
    case_id: str
    original_filename: str
    content_type: str
    size_bytes: int
    storage_mode: str = "metadata_only"
    object_key: str | None = None
    upload_status: str = "pending"
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None
    checksum_sha256: str | None = None
    uploaded_at: datetime | None = None
    storage_delete_status: str | None = None
    retained: bool = True
    created_at: datetime = Field(default_factory=utc_now)


class SignedUploadIntent(BaseModel):
    audio_file_id: str
    upload_url: str
    expires_in_seconds: int = 900
    storage_mode: str = "metadata_only"
    required_headers: dict[str, str] = Field(default_factory=dict)


class AudioUploadCompleteRequest(BaseModel):
    checksum_sha256: str | None = None
    size_bytes: int | None = None


class AudioProcessRequest(BaseModel):
    provider: str = "manual"
    draft_text: str = ""
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None


class AudioQualityReport(BaseModel):
    duration_seconds: float | None = None
    sample_rate_hz: int | None = None
    channels: int | None = None
    estimated_noise_level: float | None = None
    silence_ratio: float | None = None
    status: str
    warnings: list[str] = Field(default_factory=list)


class AsrDraftResult(BaseModel):
    provider: str
    transcript_id: str | None = None
    utterance_count: int = 0
    speaker_assignment: str = "requires_therapist_correction"
    confidence_available: bool = False
    timestamps_available: bool = False
    diarization_available: bool = False
    warnings: list[str] = Field(default_factory=list)
    quality: AudioQualityReport


class ProcessingJob(BaseModel):
    job_id: str
    session_id: str
    status: JobStatus
    message: str
    error_code: str | None = None
    details: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class ReportDraftRequest(BaseModel):
    report_type: str = "Session Review Report"
    replace_existing: bool = False


class ReportPatch(BaseModel):
    title: str | None = None
    markdown: str | None = None
    therapist_notes: str | None = None


class Report(BaseModel):
    report_id: str
    session_id: str
    case_id: str
    report_type: str
    title: str
    markdown: str
    html: str
    status: ReviewStatus = ReviewStatus.draft
    therapist_signoff_status: ReviewStatus = ReviewStatus.needs_review
    limitation_text: str = LIMITATION_TEXT
    export_timestamp: datetime | None = None
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class SignOffRequest(BaseModel):
    signed_by: str = "Demo Therapist"
    attestation: str = "I reviewed and accept responsibility for this report."


class ConsentWithdrawalRequest(BaseModel):
    reason: str
    redact_notes: bool = True


class ConsentWithdrawalResult(BaseModel):
    case_id: str
    status: ReviewStatus = ReviewStatus.withdrawn
    affected_records: dict[str, int]
    audit_message: str


PrivacyOperationType = Literal["case_export", "consent_withdrawal", "deletion_review"]
PrivacyOperationStatus = Literal["requested", "in_review", "completed", "rejected"]


class PrivacyOperationCreate(BaseModel):
    operation_type: PrivacyOperationType
    reason: str


class PrivacyOperationPatch(BaseModel):
    status: PrivacyOperationStatus | None = None
    admin_note: str | None = None


class PrivacyOperation(BaseModel):
    privacy_operation_id: str
    case_id: str
    operation_type: PrivacyOperationType
    status: PrivacyOperationStatus = "requested"
    requested_by: str
    requester_role: str = "therapist"
    reason: str
    admin_note: str = ""
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class TimelineEvent(BaseModel):
    event_id: str
    label: str
    status: ReviewStatus
    occurred_at: datetime
    target_id: str


class ExportResponse(BaseModel):
    report_id: str
    format: str
    content: str
    content_type: str = "text/markdown"
    filename: str | None = None
    encoding: str = "utf-8"
    unavailable_reason: str | None = None
    limitation_text: str = LIMITATION_TEXT


class AuditLogEntry(BaseModel):
    audit_id: str
    action: str
    target_id: str
    message: str
    timestamp: str


class AsrEvaluationInput(BaseModel):
    reference_text: str
    hypothesis_text: str
    reference_speakers: list[str] = Field(default_factory=list)
    hypothesis_speakers: list[str] = Field(default_factory=list)
    audio_duration_seconds: float = 0
    transcribed_duration_seconds: float = 0


class AsrDatasetEvaluationRequest(BaseModel):
    dataset_dir: str = "data/evaluation"
    hypothesis_dir: str | None = None
    output_dir: str | None = None


class AsrEvaluationReport(BaseModel):
    coverage: float
    utterance_count_error: int
    speaker_accuracy: float
    normalized_wer: float
    character_error_rate: float
    feature_deviation: dict[str, float]
    markdown: str
    json_report: dict[str, Any]


class AsrDatasetSampleResult(BaseModel):
    sample_id: str
    gold_transcript_path: str
    hypothesis_transcript_path: str | None = None
    audio_present: bool = False
    report: AsrEvaluationReport
    warnings: list[str] = Field(default_factory=list)


class AsrDatasetEvaluationResult(BaseModel):
    dataset_dir: str
    sample_count: int
    samples: list[AsrDatasetSampleResult]
    aggregate_metrics: dict[str, float]
    warnings: list[str] = Field(default_factory=list)
    report_paths: dict[str, str] = Field(default_factory=dict)


class ModelCardResult(BaseModel):
    path: str
    dataset_size: int
    feature_list: list[str]
    limitations: list[str]
    class_distribution: dict[str, int] = Field(default_factory=dict)
    metrics: dict[str, Any] = Field(default_factory=dict)


class DatasetBuildRequest(BaseModel):
    source_dir: str = "data/demo"
    include_unlabeled: bool = True


class FeatureTableRow(BaseModel):
    source_path: str
    label: str | None = None
    age_months: int | None = None
    sex: str | None = None
    language: str | None = None
    missing_metadata: list[str] = Field(default_factory=list)
    features: dict[str, float | int]


class DatasetBuildResult(BaseModel):
    rows: list[FeatureTableRow]
    dataset_size: int
    class_distribution: dict[str, int]
    warnings: list[str] = Field(default_factory=list)


class BaselineEvaluationRequest(BaseModel):
    source_dir: str = "data/demo"


class BaselineEvaluationResult(BaseModel):
    dataset_size: int
    class_distribution: dict[str, int]
    models: dict[str, dict[str, Any]]
    warnings: list[str] = Field(default_factory=list)


Transcript.model_rebuild()
