export function createTranscriptLine({
  line_id,
  transcript_id,
  session_id,
  case_id,
  owner_user_id,
  line_number,
  speaker,
  speaker_code = speaker,
  speaker_role = "other",
  text,
  utterance_text = text,
  reviewed_text = null,
  timing = null,
  start_time = timing?.start_time ?? null,
  end_time = timing?.end_time ?? null,
  start_ms = start_time != null ? Math.round(Number(start_time) * 1000) : null,
  end_ms = end_time != null ? Math.round(Number(end_time) * 1000) : null,
  confidence = 1.0,
  word_timestamps = [],
  clinical_flags = [],
  flags = clinical_flags,
  review_status = "needs_review",
  reviewed = false,
  interpretation_note = "",
  version = 1,
  updated_at = new Date().toISOString(),
  updated_by_user_id = null
} = {}) {
  const normalizedTiming = timing || (start_time != null || end_time != null
    ? { start_time, end_time }
    : null);

  return {
    line_id,
    transcript_id,
    session_id,
    case_id,
    owner_user_id,
    line_number,
    speaker: speaker_code,
    speaker_role,
    text: reviewed_text || utterance_text,
    utterance_text,
    reviewed_text,
    timing: normalizedTiming,
    start_ms,
    end_ms,
    confidence,
    word_timestamps,
    clinical_flags: flags,
    flags,
    review_status,
    reviewed,
    interpretation_note,
    version,
    updated_at,
    updated_by_user_id
  };
}
