export function exportCHAT(session, caseItem, transcriptLines) {
  const ageYears = Math.floor((caseItem?.age_months || 48) / 12);
  const ageMonths = String((caseItem?.age_months || 48) % 12).padStart(2, "0");
  const sex = caseItem?.sex === "male" || caseItem?.sex === "female" ? caseItem.sex : "";

  let chat = `@Begin
@Languages:\teng
@Participants:\tCHI Child Target_Child, MOT Mother Mother, INV Investigator Investigator
@ID:\tteng|Mock|CHI|${ageYears};${ageMonths}.00|${sex}|||Target_Child|||
@ID:\tteng|Mock|MOT|||||Mother|||
@ID:\tteng|Mock|INV|||||Investigator|||
@Comment:\tThis file was generated by the AI-Assisted Speech-Language Screening Support prototype. It is CHAT-inspired and does not represent a certified TalkBank format.
`;

  if (transcriptLines && transcriptLines.length) {
    transcriptLines.forEach(line => {
      const spk = line.speaker === "CHI" ? "*CHI" : (line.speaker === "MOT" ? "*MOT" : "*INV");
      chat += `${spk}:\t${line.text}\n`;
    });
  } else {
    chat += `*CHI:\twant car .\n*MOT:\twhich car do you want ?\n*CHI:\tred car .\n`;
  }

  chat += `@End`;
  return chat;
}

export function exportJSON(session, caseItem, transcriptLines, features, aiOutput) {
  return {
    export_metadata: {
      generated_at: new Date().toISOString(),
      disclaimer: "This structured dataset is for clinical decision-support only. It is not an automated diagnosis and requires clinical interpretation."
    },
    case: {
      case_id: caseItem?.case_id,
      anonymized_child_code: caseItem?.anonymized_child_code,
      age_months: caseItem?.age_months,
      sex: caseItem?.sex
    },
    session: {
      session_id: session.session_id,
      session_date: session.session_date,
      session_type: session.session_type,
      notes: session.notes
    },
    transcript: transcriptLines || [],
    linguistic_features: features || null,
    decision_support: aiOutput || null
  };
}
