"""Generate frontend mock data from selected local CHAT transcripts."""

from __future__ import annotations

import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from packages.cha.parser import parse_cha_file  # noqa: E402
from src.clinical_speech.feature_extractor import extract_clinical_features  # noqa: E402
from src.feature_schema import FEATURES  # noqa: E402


FEATURES_CSV = PROJECT_ROOT / "data" / "reference" / "english_child_reference_features.csv"
OUTPUT_PATH = PROJECT_ROOT / "therapist-clinician-app" / "src" / "store" / "cha-reference-mock-data.js"

SELECTED_TRANSCRIPTS = [
    {
        "source_path": "data/Eigsti/ASD/1012.cha",
        "case_id": "CASE-CHA-ASD-1012",
        "session_id": "SESSION-CHA-EIGSTI-1012",
        "transcript_id": "TRANSCRIPT-CHA-EIGSTI-1012",
        "feature_id": "FEATURE-CHA-EIGSTI-1012",
        "output_id": "AI-OUTPUT-CHA-EIGSTI-1012",
        "date": "2026-05-29",
        "support_level": "Reference review",
        "latest_score": 0.68,
        "probabilities": {"ASD": 0.68, "DD": 0.19, "TD": 0.13},
    },
    {
        "source_path": "data/Eigsti/DD/1030.cha",
        "case_id": "CASE-CHA-DD-1030",
        "session_id": "SESSION-CHA-EIGSTI-1030",
        "transcript_id": "TRANSCRIPT-CHA-EIGSTI-1030",
        "feature_id": "FEATURE-CHA-EIGSTI-1030",
        "output_id": "AI-OUTPUT-CHA-EIGSTI-1030",
        "date": "2026-05-30",
        "support_level": "Reference review",
        "latest_score": 0.55,
        "probabilities": {"DD": 0.55, "ASD": 0.28, "TD": 0.17},
    },
    {
        "source_path": "data/Eigsti/TD/1011.cha",
        "case_id": "CASE-CHA-TD-1011",
        "session_id": "SESSION-CHA-EIGSTI-1011",
        "transcript_id": "TRANSCRIPT-CHA-EIGSTI-1011",
        "feature_id": "FEATURE-CHA-EIGSTI-1011",
        "output_id": "AI-OUTPUT-CHA-EIGSTI-1011",
        "date": "2026-05-31",
        "support_level": "Reference review",
        "latest_score": 0.21,
        "probabilities": {"TD": 0.79, "DD": 0.14, "ASD": 0.07},
    },
]
MAX_UTTERANCES_PER_TRANSCRIPT = 40


def main() -> None:
    feature_rows = _load_feature_rows()
    cases: list[str] = []
    sessions: list[str] = []
    transcript_lines: dict[str, list[dict[str, Any]]] = {}
    transcript_records: dict[str, str] = {}
    feature_outputs: dict[str, dict[str, Any]] = {}
    ai_outputs: dict[str, dict[str, Any]] = {}
    session_vocabs: dict[str, list[dict[str, Any]]] = {}

    for config in SELECTED_TRANSCRIPTS:
        source_path = config["source_path"]
        row = feature_rows[source_path]
        parsed = parse_cha_file(PROJECT_ROOT / source_path)
        utterances = _select_utterances(parsed.utterances)
        case = _case(config, row)
        session = _session(config)
        transcript_text = _chat_text(parsed, utterances)

        cases.append(f"  createChildCase({_js(case)})")
        sessions.append(f"  createSession({_js(session)})")
        transcript_lines[config["session_id"]] = _lines(config, utterances)
        transcript_records[config["session_id"]] = (
            f"createTranscript({_js(_transcript(config, row, transcript_text))})"
        )
        feature_outputs[config["session_id"]] = _feature_output(config, row, utterances)
        ai_outputs[config["session_id"]] = _ai_output(config, row)
        session_vocabs[config["session_id"]] = _vocab(utterances)

    OUTPUT_PATH.write_text(
        "\n".join(
            [
                "// Generated by scripts/build_cha_reference_mock_data.py.",
                "// Derived from local CHAT (.cha) reference transcripts for mock-mode demos.",
                "",
                "import { createChildCase, createSession, createTranscript } from \"@shared/models\";",
                "",
                "export const mockChaReferenceCases = [",
                ",\n".join(cases),
                "];",
                "",
                "export const mockChaReferenceSessions = [",
                ",\n".join(sessions),
                "];",
                "",
                f"export const mockChaReferenceTranscriptLines = {_js(transcript_lines)};",
                "",
                "export const mockChaReferenceTranscriptRecords = {",
                ",\n".join(
                    f"  {json.dumps(session_id)}: {factory}"
                    for session_id, factory in transcript_records.items()
                ),
                "};",
                "",
                f"export const mockChaReferenceExtractedFeatureOutputs = {_js(feature_outputs)};",
                "",
                f"export const mockChaReferenceAiDecisionOutputs = {_js(ai_outputs)};",
                "",
                f"export const mockChaReferenceSessionVocabs = {_js(session_vocabs)};",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _load_feature_rows() -> dict[str, dict[str, str]]:
    with FEATURES_CSV.open(newline="", encoding="utf-8") as handle:
        return {row["source_path"]: row for row in csv.DictReader(handle)}


def _case(config: dict[str, Any], row: dict[str, str]) -> dict[str, Any]:
    group = row["group"]
    source = config["source_path"]
    return {
        "case_id": config["case_id"],
        "owner_user_id": "user_therapist_001",
        "anonymized_child_code": f"REF-{row['corpus'].upper()}-{Path(source).stem}",
        "display_label": f"{row['corpus']} {Path(source).stem} reference sample",
        "age_months": int(round(float(row["age_months"]))),
        "sex": _sex(row["sex"]),
        "primary_concerns": (
            f"Reference cohort sample from {row['corpus']} ({row['task_type']}, cohort {group}). "
            "Use for mock workflow review only; not a diagnosis."
        ),
        "external_clinical_status": "not_provided",
        "consent_status": "granted",
        "anonymization_status": "anonymized",
        "support_level": config["support_level"],
        "latest_score": config["latest_score"],
        "score_trend": [round(max(config["latest_score"] - 0.08, 0), 2), config["latest_score"]],
        "starred": False,
        "notes": (
            f"Source .cha: {source}. Reference Cohort Label={group}; "
            "label is retained for cohort comparison context only."
        ),
        "created_at": f"{config['date']}T09:00:00Z",
        "updated_at": f"{config['date']}T10:00:00Z",
    }


def _session(config: dict[str, Any]) -> dict[str, Any]:
    return {
        "session_id": config["session_id"],
        "case_id": config["case_id"],
        "owner_user_id": "user_therapist_001",
        "session_date": config["date"],
        "session_type": "structured_assessment",
        "audio_file_id": None,
        "transcript_id": config["transcript_id"],
        "processing_status": "transcript_ready",
        "feature_extraction_status": "completed",
        "ai_analysis_status": "completed",
        "therapist_review_status": "awaiting_review",
        "report_status": "pending",
        "notes": "Mock session generated from a local CHAT reference transcript.",
        "created_at": f"{config['date']}T09:10:00Z",
        "updated_at": f"{config['date']}T10:00:00Z",
    }


def _transcript(config: dict[str, Any], row: dict[str, str], transcript_text: str) -> dict[str, Any]:
    source = config["source_path"]
    return {
        "transcript_id": config["transcript_id"],
        "session_id": config["session_id"],
        "case_id": config["case_id"],
        "owner_user_id": "user_therapist_001",
        "original_filename": Path(source).name,
        "transcript_text": transcript_text,
        "review_status": "awaiting_review",
        "qa_status": "pass",
        "qa_score": 100,
        "qa_issues": [],
        "reviewer_notes": f"Generated from {source}; Reference Cohort Label={row['group']}.",
        "created_at": f"{config['date']}T09:15:00Z",
        "updated_at": f"{config['date']}T10:00:00Z",
    }


def _select_utterances(utterances: list[Any]) -> list[Any]:
    return utterances[:MAX_UTTERANCES_PER_TRANSCRIPT]


def _lines(config: dict[str, Any], utterances: list[Any]) -> list[dict[str, Any]]:
    rows = []
    for index, utterance in enumerate(utterances, start=1):
        rows.append(
            {
                "line_id": f"{config['transcript_id']}_L{index:04d}",
                "transcript_id": config["transcript_id"],
                "session_id": config["session_id"],
                "case_id": config["case_id"],
                "owner_user_id": "user_therapist_001",
                "line_number": index,
                "speaker": utterance.speaker_code,
                "speaker_role": utterance.speaker_role,
                "text": utterance.raw_text,
                "utterance_text": utterance.raw_text,
                "confidence": 1.0,
                "timing": _timing(utterance),
                "start_ms": utterance.start_ms,
                "end_ms": utterance.end_ms,
                "review_status": "needs_review",
                "reviewed": False,
            }
        )
    return rows


def _feature_output(config: dict[str, Any], row: dict[str, str], utterances: list[Any]) -> dict[str, Any]:
    extracted = extract_clinical_features(
        [utterance.to_normalized_line(session_id=config["session_id"]) for utterance in utterances],
        age_months=_number(row.get("age_months", 0)),
    )
    features = {feature: extracted["features"].get(feature, 0) for feature in FEATURES}
    return {
        "feature_id": config["feature_id"],
        "session_id": config["session_id"],
        "case_id": config["case_id"],
        "owner_user_id": "user_therapist_001",
        "feature_schema_version": "14-feature-schema",
        "extraction_status": "completed",
        "created_at": f"{config['date']}T09:20:00Z",
        "features": features,
        "source": {
            "source_path": config["source_path"],
            "corpus": row["corpus"],
            "reference_cohort_label": row["group"],
            "task_type": row["task_type"],
            "mock_scope": f"first {MAX_UTTERANCES_PER_TRANSCRIPT} main CHAT tiers",
        },
    }


def _ai_output(config: dict[str, Any], row: dict[str, str]) -> dict[str, Any]:
    probabilities = config["probabilities"]
    most_similar = max(probabilities, key=probabilities.get)
    source = config["source_path"]
    return {
        "output_id": config["output_id"],
        "session_id": config["session_id"],
        "case_id": config["case_id"],
        "owner_user_id": "user_therapist_001",
        "concern_level": "watchful_review" if most_similar != "TD" else "no_concern",
        "screening_support_score": round(float(probabilities[most_similar]), 2),
        "reference_cohort_probabilities": probabilities,
        "most_similar_reference_cohort": most_similar,
        "reference_cohort_label": row["group"],
        "inference_status": "preliminary",
        "report_eligible": False,
        "top_contributing_features": ["mluw", "ttr", "unintelligible_ratio"],
        "evidence_items": [
            f"Source transcript: {source}",
            f"Reference cohort label retained from corpus metadata: {row['group']}",
            "Preliminary mock output; review transcript context before interpretation.",
        ],
        "explanation": (
            f"This mock output shows reference cohort similarity for {Path(source).name}. "
            "It is clinical decision support only and is not a diagnosis."
        ),
        "therapist_review_status": "awaiting_review",
        "created_at": f"{config['date']}T09:25:00Z",
    }


def _vocab(utterances: list[Any]) -> list[dict[str, Any]]:
    tokens = [
        token
        for utterance in utterances
        if utterance.speaker_role == "child"
        for token in utterance.tokens
    ]
    return [
        {"word": word, "count": count, "type": "token", "isNew": False}
        for word, count in Counter(tokens).most_common(12)
    ]


def _chat_text(parsed: Any, utterances: list[Any]) -> str:
    lines = ["@Begin"]
    for header_key in ["@Languages", "@Participants", "@ID", "@Types"]:
        for value in parsed.headers.get(header_key, []):
            lines.append(f"{header_key}:\t{value}")
    for utterance in utterances:
        lines.append(f"*{utterance.speaker_code}:\t{utterance.raw_text}")
    lines.append("@End")
    return "\n".join(lines)


def _timing(utterance: Any) -> dict[str, float | None] | None:
    if utterance.start_ms is None and utterance.end_ms is None:
        return None
    return {
        "start_time": utterance.start_ms / 1000 if utterance.start_ms is not None else None,
        "end_time": utterance.end_ms / 1000 if utterance.end_ms is not None else None,
    }


def _sex(value: str) -> str:
    normalized = value.strip().lower()
    if normalized in {"male", "female"}:
        return normalized
    return "not_specified"


def _number(value: Any) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return 0.0
    return int(number) if number.is_integer() else number


def _js(value: Any) -> str:
    return re.sub(r'"([A-Za-z_$][A-Za-z0-9_$]*)":', r"\1:", json.dumps(value, ensure_ascii=True, indent=2))


if __name__ == "__main__":
    main()
