"""Stable v1.7.0 QA issue classification for the speech testbed."""

QA_RULE_VERSION = "speech-qa-v1.7.0"

INTEGRITY_BLOCKER_CODES = frozenset(
    {
        "SOURCE_AUDIO_MISSING", "SOURCE_AUDIO_UNVERIFIED", "NORMALIZED_AUDIO_MISSING",
        "NORMALIZED_AUDIO_CORRUPT", "NORMALIZED_AUDIO_TRUNCATED", "AUDIO_LINEAGE_MISMATCH",
        "AUDIO_CHECKSUM_MISMATCH", "AUDIO_SIZE_LIMIT_EXCEEDED", "AUDIO_DURATION_LIMIT_EXCEEDED",
        "TRANSCRIPT_AUDIO_VERSION_MISMATCH", "TRANSCRIPT_STALE", "SPEAKER_MAPPING_MISSING",
        "SPEAKER_MAPPING_STALE", "SPEAKER_MAPPING_INCOMPLETE", "SPEAKER_MAPPING_AMBIGUOUS",
        "SEGMENT_SPEAKER_UNMAPPED", "TIMESTAMP_ORDER_INVALID", "TIMESTAMP_RANGE_INVALID",
        "TIMESTAMP_OVERLAP_INVALID", "BEGINNING_COVERAGE_FAILED", "ENDING_COVERAGE_FAILED",
        "TRANSCRIPT_MATERIALLY_INCOMPLETE", "TRANSCRIPT_EMPTY", "ATTESTATION_VERSION_STALE",
        "CHAT_ROUND_TRIP_FAILED", "CHAT_CONTENT_MUTATED", "CHAT_UNSUPPORTED_CONTENT_BLOCKING",
        "PROVENANCE_VERSION_MISMATCH", "CONSENT_INVALID", "ACCESS_UNAUTHORIZED",
        "UPSTREAM_JOB_FAILED", "UPSTREAM_PARTIAL_UNSAFE",
    }
)

LEGACY_BLOCKER_MAP = {
    "MISSING_BEGIN": "TRANSCRIPT_MATERIALLY_INCOMPLETE",
    "MISSING_END": "TRANSCRIPT_MATERIALLY_INCOMPLETE",
    "MISSING_CHILD_SPEAKER": "SPEAKER_MAPPING_INCOMPLETE",
    "UNKNOWN_SPEAKER": "SEGMENT_SPEAKER_UNMAPPED",
    "MALFORMED_LINE_SPEAKER_LIKE": "TRANSCRIPT_MATERIALLY_INCOMPLETE",
    "TIMESTAMP_ORDER": "TIMESTAMP_ORDER_INVALID",
    "TIMESTAMP_OUT_OF_RANGE": "TIMESTAMP_RANGE_INVALID",
    "TIMESTAMP_OVERLAP": "TIMESTAMP_OVERLAP_INVALID",
}

LIMITATION_MAP = {
    "SHORT_TRANSCRIPT": "SHORT_SAMPLE",
    "TOO_FEW_CHILD_UTTERANCES": "SHORT_SAMPLE",
    "HIGH_UNINTELLIGIBLE_RATIO": "LOW_INTELLIGIBILITY",
    "MISSING_LANGUAGE": "OPTIONAL_CHAT_METADATA_ABSENT",
    "MISSING_PARTICIPANTS": "OPTIONAL_CHAT_METADATA_ABSENT",
    "UNSUPPORTED_DEPENDENT_TIER": "OPTIONAL_FEATURE_UNAVAILABLE",
    "MISSING_TIMESTAMPS": "BELOW_TARGET_TIMESTAMP_COVERAGE",
    "LOW_TRANSCRIPT_COVERAGE": "BELOW_TARGET_TIMESTAMP_COVERAGE",
    "HIGH_UNKNOWN_SPEAKER_RATIO": "MANUAL_MAPPING_REQUIRED",
    "UNSUPPORTED_LANGUAGE": "INTERPRETATION_LIMITING_AUDIO_OR_LANGUAGE_QUALITY",
    "CODE_SWITCHING_WARNING": "INTERPRETATION_LIMITING_AUDIO_OR_LANGUAGE_QUALITY",
}

LIMITATION_REMEDIATION = {
    "SHORT_SAMPLE": "Confirm that the reviewed excerpt is the intended sample and interpret counts cautiously.",
    "LOW_INTELLIGIBILITY": "Review uncertain utterances and confirm the retained text before attestation.",
    "OPTIONAL_CHAT_METADATA_ABSENT": "Add the optional CHAT metadata when it is known, or acknowledge its absence.",
    "OPTIONAL_FEATURE_UNAVAILABLE": "Keep the preserved content visible and do not infer an unavailable metric.",
    "BELOW_TARGET_TIMESTAMP_COVERAGE": "Review valid timestamp coverage and acknowledge that time-based metrics may be unavailable.",
    "MANUAL_MAPPING_REQUIRED": "Complete and confirm therapist-reviewed speaker mapping.",
    "INTERPRETATION_LIMITING_AUDIO_OR_LANGUAGE_QUALITY": "Review language and audio context and record the interpretation limitation.",
}
